# Generated by Django 4.2.14 on 2024-09-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('contact_number', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('enquiry_text', models.CharField(max_length=1000)),
                ('enq_date', models.DateTimeField()),
            ],
        ),
    ]
