# Generated by Django 4.2.14 on 2024-09-10 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSMyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='enq_date',
            new_name='enquiry_date',
        ),
    ]
