# Generated by Django 4.2.14 on 2024-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSMyApp', '0002_rename_enq_date_enquiry_enquiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_data',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('passkey', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
