# Generated by Django 4.2.14 on 2024-09-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSMyApp', '0003_admin_data_alter_enquiry_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_data',
            new_name='admin_login',
        ),
    ]
