# Generated by Django 4.2.14 on 2024-09-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSMyApp', '0004_rename_admin_data_admin_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_login',
            new_name='admin_data',
        ),
    ]
