# Generated by Django 4.2.14 on 2024-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_class', models.CharField(max_length=50)),
                ('subject_book', models.CharField(max_length=50)),
                ('subject_techer', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_subjects',
            field=models.CharField(max_length=100),
        ),
    ]
