# Generated by Django 4.2.14 on 2024-09-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_subjects_alter_classes_class_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_father_name', models.CharField(max_length=50)),
                ('teacher_mother_name', models.CharField(max_length=50)),
                ('teacher_gender', models.CharField(max_length=50)),
                ('teacher_dob', models.DateField()),
                ('teacher_phone', models.IntegerField(max_length=15)),
                ('teacher_email', models.EmailField(max_length=100)),
                ('teacher_password', models.CharField(max_length=50)),
                ('teacher_allocated_classes', models.CharField(max_length=1000)),
                ('teacher_address', models.CharField(max_length=50)),
                ('teacher_salary', models.IntegerField(max_length=70)),
                ('teacher_qualification', models.CharField(max_length=500)),
                ('teacher_profile_image', models.ImageField(upload_to='')),
                ('teacher_joining_date', models.DateTimeField()),
            ],
        ),
    ]
