# Generated by Django 4.2.15 on 2024-09-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_enrollment_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('student_adhar', models.IntegerField(max_length=12)),
                ('student_name', models.CharField(max_length=50)),
                ('student_father_name', models.CharField(max_length=50)),
                ('student_mother_name', models.CharField(max_length=50)),
                ('student_gender', models.CharField(max_length=50)),
                ('student_dob', models.DateField()),
                ('student_phone', models.IntegerField(max_length=15)),
                ('student_parents_phone', models.IntegerField(max_length=15)),
                ('student_email', models.EmailField(max_length=100)),
                ('student_password', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=1000)),
                ('student_address', models.CharField(max_length=50)),
                ('student_fee', models.IntegerField(max_length=70)),
                ('student_subjects', models.CharField(max_length=500)),
                ('student_profile_image', models.ImageField(upload_to='')),
                ('student_admission_date', models.DateTimeField()),
            ],
        ),
    ]
