# Generated by Django 4.2.15 on 2024-09-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('attendence_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_attendence_id', models.CharField(max_length=150)),
                ('student_attendence_enrollment_id', models.IntegerField()),
                ('student_attendence_name', models.CharField(max_length=50)),
                ('student_attendence_email', models.EmailField(max_length=100)),
                ('student_attendence_class', models.CharField(max_length=50)),
                ('student_attendence_class_teacher', models.CharField(max_length=1000)),
                ('student_attendence_status', models.CharField(max_length=1)),
                ('student_attendence_date', models.DateField()),
            ],
        ),
    ]
