# Generated by Django 4.2.15 on 2024-09-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_serial_no',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='student_adhar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_phone',
            field=models.IntegerField(),
        ),
    ]
