# Generated by Django 4.2.15 on 2024-09-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_students_student_serial_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_serial_no',
            field=models.IntegerField(),
        ),
    ]
