# Generated by Django 4.2.15 on 2024-09-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0007_alter_students_student_serial_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("notification_msg", models.CharField(max_length=500000)),
                ("notification_date", models.DateField()),
            ],
        ),
    ]
