# Generated by Django 4.2.15 on 2024-09-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0008_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="notification_document",
            field=models.FileField(default=1, upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notifications",
            name="notification_msg",
            field=models.TextField(),
        ),
    ]
