# Generated by Django 4.2.15 on 2024-09-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0009_notifications_notification_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="student_serial_no",
        ),
    ]
