# Generated by Django 4.2.15 on 2024-09-18 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Study_Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Document_title", models.CharField(max_length=10)),
                ("Document_location", models.FileField(upload_to="")),
                ("Uploaded_date", models.DateField(default=datetime.date(2024, 9, 18))),
            ],
        ),
    ]
