# Generated by Django 4.2.15 on 2024-09-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TeacherApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="study_material",
            name="Document_for_class",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
