# Generated by Django 4.2.15 on 2024-09-19 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TeacherApp", "0002_study_material_document_for_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study_material",
            name="Uploaded_date",
            field=models.DateField(default=datetime.date(2024, 9, 19)),
        ),
    ]
